### ISSUE TITLE
install.sh: 32: Syntax error: "(" unexpected`

### ISSUE THREAD

**Issue by ezequieltejada** [jarrodcolburn/features#7]
Hi @jarrodcolburn,

First of all, thank you for the feature! Let me share an issue I've found.

When trying to create a container with the following customizations:

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
{
	"name": "Debian",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/vscode/devcontainers/base:0-debian-11",
	"features": {
		"ghcr.io/devcontainers/features/python:1": {},
		"ghcr.io/devcontainers-contrib/features/angular-cli:2": {},
		"ghcr.io/devcontainers/features/node:1": {},
		"ghcr.io/akhildevelops/devcontainer-features/android-cli:0": {},
		"ghcr.io/jarrodcolburn/features/android-sdk:0": {},
		"ghcr.io/devcontainers/features/java:1": {},
		"ghcr.io/devcontainers-contrib/features/ionic-cli:2": {}
	}

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "uname -a",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}

```

I got this error message:

```
[2023-03-28T06:10:29.599Z] #0 75.50 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#0 75.50 
#0 98.97 ./install.sh: 32: Syntax error: "(" unexpected
[2023-03-28T06:10:29.599Z] #0 98.97 ERROR: Feature "Android SDK" (ghcr.io/jarrodcolburn/features/android-sdk) failed to install!
[2023-03-28T06:10:29.599Z] ------
[2023-03-28T06:10:29.615Z] ERROR: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/android-sdk_5 /tmp/build-features/  && chmod -R 0700 /tmp/build-features/android-sdk_5  && cd /tmp/build-features/android-sdk_5  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/build-features/android-sdk_5]: exit code: 2
[2023-03-28T06:10:29.988Z] Stop (644252 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-etejada/container-features/0.31.0-1679983179701 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/base:0-debian-11 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-wfiguiarapidaapp-b8c094115aa72d0199adc1f750781a74-features -f /tmp/devcontainercli-etejada/container-features/0.31.0-1679983179701/Dockerfile.extended /tmp/devcontainercli-etejada/empty-folder
[2023-03-28T06:10:30.008Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-etejada/container-features/0.31.0-1679983179701 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/base:0-debian-11 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-wfiguiarapidaapp-b8c094115aa72d0199adc1f750781a74-features -f /tmp/devcontainercli-etejada/container-features/0.31.0-1679983179701/Dockerfile.extended /tmp/devcontainercli-etejada/empty-folder
[2023-03-28T06:10:30.008Z]     at cie (/home/etejada/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1930:3293)
[2023-03-28T06:10:30.009Z]     at S7 (/home/etejada/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1930:3229)
[2023-03-28T06:10:30.009Z]     at runMicrotasks (<anonymous>)
[2023-03-28T06:10:30.009Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-03-28T06:10:30.009Z]     at async xie (/home/etejada/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:2625)
[2023-03-28T06:10:30.009Z]     at async Wf (/home/etejada/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:3750)
[2023-03-28T06:10:30.010Z]     at async noe (/home/etejada/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17325)
[2023-03-28T06:10:30.010Z]     at async roe (/home/etejada/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17066)
[2023-03-28T06:10:30.061Z] Stop (651998 ms): Run in Host: /home/etejada/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node /home/etejada/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-fe6b31be-bc9a-41ec-974e-ed09ac3f246e1679983175528 --workspace-folder /home/etejada/DEV/IZFE/WFIGuiaRapidaAPP --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-22.04\home\etejada\DEV\IZFE\WFIGuiaRapidaAPP --id-label devcontainer.config_file=/home/etejada/DEV/IZFE/WFIGuiaRapidaAPP/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/etejada/DEV/IZFE/WFIGuiaRapidaAPP/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/mnt/wslg/runtime-dir/wayland-0,target=/tmp/vscode-wayland-cf9fb6ce-fe46-480f-b817-bd35e954e98e.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-28T06:10:30.062Z] Exit code 1
[2023-03-28T06:10:30.069Z] Command failed: /home/etejada/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node /home/etejada/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-fe6b31be-bc9a-41ec-974e-ed09ac3f246e1679983175528 --workspace-folder /home/etejada/DEV/IZFE/WFIGuiaRapidaAPP --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-22.04\home\etejada\DEV\IZFE\WFIGuiaRapidaAPP --id-label devcontainer.config_file=/home/etejada/DEV/IZFE/WFIGuiaRapidaAPP/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/etejada/DEV/IZFE/WFIGuiaRapidaAPP/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/mnt/wslg/runtime-dir/wayland-0,target=/tmp/vscode-wayland-cf9fb6ce-fe46-480f-b817-bd35e954e98e.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-28T06:10:30.069Z] Exit code 1
[2023-03-28T06:10:45.023Z] Start: Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\etejada\DEV\IZFE\WFIGuiaRapidaAPP
[2023-03-28T06:10:45.416Z] Stop (393 ms): Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\etejada\DEV\IZFE\WFIGuiaRapidaAPP
```

Since it says `#0 98.97 ./install.sh: 32: Syntax error: "(" unexpected` I report it just in case. I had to remove the feature to continue.

**Comment by natterstefan** [comment]
Hi @ezequieltejada,

I just had the same issue...

Hi @jarrodcolburn.

Any chance you can take a look at this, please? It seems to be related to this commit https://github.com/jarrodcolburn/features/commit/50e2c251fb8c668fe020e1bc028547542eb380cc.

**Comment by jarrodcolburn** [comment]
@natterstefan @ezequieltejada 

Hey guys, sorry. Unfortunately, I just submitted a PR to remove flutter package from public devcontainers. 

I'm in the middle of a big project and won't have time to return to it for another month at least, and I feel having my flutter package listed as is does more harm than good.  Feel free to fork and publish if you wan't, I'd love to work on when have more time, I think it's an important dev container.

I wished the feature was ready for the project I'm working on currently, but I just had to fall back to using dev machine due to issues myself. 

sorry again,
